### PR TITLE
Tf25 t27

### PR DESCRIPTION
**Pull request by urt23**
1. Implemented Publish form
  - Added a new column "Published " to forms table
  - added verifications to check if the form contains necessary attributes before publishing the form
  - 100 % rspec covered
  - added seeds for demo purpose

2. Implemented calculate number of teams
  - returns number of teams of 4, teams of 3, total # of students and their form responses, corresponding to each course section for a given form.
  - 100 % rspec covered
3. Rubocop checked, all cops.

### CODE REVIEW

**Review by Sahithi1214 — APPROVED** [review]
Approving

**Review by rithikasapparapu — APPROVED** [review]
Approving

**Comment by urt23** [comment]
Uploading Screen Recording 2024-10-17 at 1.29.04 AM.mov…

**Comment by urt23** [comment]
https://github.com/user-attachments/assets/a5736967-9929-4382-9e28-79a313d8665e

**Pull request merged**
