### PR TITLE
Tf78

### PR DESCRIPTION
**Pull request by phanijyothi11-tamu**

### CODE REVIEW

**Comment by phanijyothi11-tamu** [comment]
The following issues have been fixed under this ticket for Duplicate Form button:
When the Prof clicks on duplicate form, a copy of existing form will be created without opening/ redirecting to a new tab (earlier implementation redirected to new tab).
The naming convention of forms changed to "Copy of Form", "Copy of Copy of Form".
Cucumber and rspec have been covered for the same.

**Comment by phanijyothi11-tamu** [comment]
https://github.com/user-attachments/assets/5ebd53be-dabe-4c3c-a702-ac3648242e83
please go through the video recording link for ref.

**Review by raju2102 — APPROVED** [review]

**Review by muresaijaideepreddy — APPROVED** [review]

**Review by muresaijaideepreddy — APPROVED** [review]

**Comment by phanijyothi11-tamu** [comment]
The functionality implemented in this ticket is where we create multiple copies of the form, succeeding the duplicates , previously the duplicate on the form can be achieved only once but now even if the user clicks multiple times we create multiple duplicates checking the form names are unique and not overlapping.Covering rspec and cucumber for the same.
Please review the video recording attached for ref. 

https://github.com/user-attachments/assets/8ef9954d-27b6-40a7-9d83-1d05c79ba846

**Comment by phanijyothi11-tamu** [comment]
https://github.com/user-attachments/assets/8d8e944d-a396-4280-b8e4-7923b07cd77a

(updated recording) please review

**Review by urt23 — APPROVED** [review]

**Review by muresaijaideepreddy — APPROVED** [review]

**Pull request merged**
