### PR TITLE
Tf10 tf11

### PR DESCRIPTION
**Pull request by hithamv**
This pull request covers the cucumber and rspec test cases for preview and duplicate

### CODE REVIEW

**Review by phanijyothi11-tamu — APPROVED** [review]
Approving changes

**Review by phanijyothi11-tamu — APPROVED** [review]
Approved

**Review by muresaijaideepreddy — COMMENTED** [review]
Approved

**Review by muresaijaideepreddy — COMMENTED** [review]
Approve

**Review by muresaijaideepreddy — APPROVED** [review]
Approve

**Pull request merged**
